name: Build
on: [push, pull_request, merge_group]
jobs:
  build:
    strategy:
      matrix:
        java: [21-ubuntu]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - run: ./gradlew check build --stacktrace