  name: Publish Mod
  on:
    workflow_dispatch:

  permissions:
    contents: write

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Resources
          uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 21

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.4.2

        - name: Build and Publish
          run: ./gradlew build publishMods --stacktrace
          env:
            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
